import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: "#F3F4F4",
  },
  container: {
    flex: 1,
    paddingHorizontal: 18,
    paddingTop: 6,
    paddingBottom: 18,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backBtn: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  topBarTitle: {
    fontSize: 18,
    color: "#1F2937",
    fontWeight: "700",
  },
  topSpacer: {
    width: 40,
  },
  headerBlock: {
    marginTop: 14,
  },
  title: {
    fontSize: 24,
    color: "#111827",
    fontWeight: "800",
  },
  subtitle: {
    marginTop: 8,
    color: "#5F6672",
    lineHeight: 26,
    fontSize: 14,
  },
  uploadBox: {
    marginTop: 18,
    height: 236,
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: "#4F7EE8",
    borderRadius: 20,
    backgroundColor: "#F7F7F7",
    overflow: "hidden",
    justifyContent: "center",
    alignItems: "center",
  },
  uploadInner: {
    alignItems: "center",
    justifyContent: "center",
  },
  uploadIconWrap: {
    width: 74,
    height: 74,
    borderRadius: 37,
    backgroundColor: "#E5E7EB",
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 14,
  },
  uploadText: {
    fontSize: 16,
    color: "#111827",
    fontWeight: "700",
    lineHeight: 24,
  },
  previewImage: {
    width: "100%",
    height: "100%",
  },
  actionRow: {
    flexDirection: "row",
    gap: 12,
    marginTop: 18,
  },
  secondaryBtn: {
    flex: 1,
    height: 50,
    borderRadius: 14,
    borderWidth: 1.5,
    borderColor: "#B7B7B7",
    backgroundColor: "#F8F8F8",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  secondaryBtnText: {
    color: "#1F2937",
    fontSize: 15,
    fontWeight: "700",
  },
  mobileCamBtn: {
    flex: 1,
    height: 50,
    borderRadius: 14,
    backgroundColor: "#DDE6EF",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  mobileCamBtnText: {
    color: "#0B3D91",
    fontSize: 15,
    fontWeight: "700",
  },
  primaryBtn: {
    marginTop: 16,
    height: 52,
    borderRadius: 14,
    backgroundColor: "#0B3D91",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 10,
  },
  primaryBtnDisabled: {
    opacity: 0.7,
  },
  primaryBtnText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "800",
  },
  tipsCard: {
    marginTop: 18,
    backgroundColor: "#F8F8F8",
    borderRadius: 20,
    padding: 14,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  tipsHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
    gap: 8,
  },
  tipsHeaderIcon: {
    width: 20,
    height: 20,
    borderRadius: 6,
    backgroundColor: "#DCE7F5",
    alignItems: "center",
    justifyContent: "center",
  },
  tipsHeaderText: {
    fontSize: 14,
    color: "#111827",
    fontWeight: "800",
  },
  tipItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#DDE6EF",
    borderRadius: 14,
    padding: 14,
    marginTop: 10,
    gap: 12,
  },
  tipIconBox: {
    width: 48,
    height: 48,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
  },
  tipIconBlue: {
    backgroundColor: "#DCE7F5",
  },
  tipIconOrange: {
    backgroundColor: "#F4DFC8",
  },
  tipContent: {
    flex: 1,
  },
  tipTitle: {
    fontSize: 15,
    color: "#111827",
    fontWeight: "800",
  },
  tipDesc: {
    marginTop: 4,
    fontSize: 13,
    color: "#374151",
  },
});