import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: "#F3F4F4",
  },
  container: {
    paddingHorizontal: 14,
    paddingTop: 6,
    paddingBottom: 24,
  },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  backBtn: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  topBarTitle: {
    fontSize: 17,
    color: "#111827",
    fontWeight: "800",
  },
  topSpacer: {
    width: 40,
  },
  imageCard: {
    position: "relative",
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "#E5E7EB",
  },
  image: {
    width: "100%",
    height: 170,
    borderRadius: 16,
  },
  imageFallback: {
    width: "100%",
    height: 170,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
  },
  plantTag: {
    position: "absolute",
    top: 10,
    left: 10,
    backgroundColor: "#F1F5F9",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  plantTagText: {
    fontSize: 11,
    color: "#111827",
    fontWeight: "800",
  },
  timeTag: {
    position: "absolute",
    bottom: 10,
    right: 10,
    backgroundColor: "rgba(17,24,39,0.55)",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  timeTagText: {
    fontSize: 11,
    color: "#fff",
    fontWeight: "700",
  },
  scoreCard: {
    marginTop: 10,
    backgroundColor: "#F5F5F5",
    borderRadius: 16,
    padding: 14,
  },
  smallMuted: {
    fontSize: 11,
    color: "#94A3B8",
    fontWeight: "800",
    letterSpacing: 0.5,
  },
  scoreRow: {
    marginTop: 4,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  scoreText: {
    fontSize: 52,
    lineHeight: 56,
    fontWeight: "900",
  },
  statusPill: {
    marginTop: 2,
    alignSelf: "flex-start",
    paddingHorizontal: 8,
    paddingVertical: 3,
    borderRadius: 999,
  },
  statusPillText: {
    fontSize: 11,
    fontWeight: "800",
  },
  warningIconWrap: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: "#D8E2F2",
    justifyContent: "center",
    alignItems: "center",
  },
  metaText: {
    marginTop: 6,
    color: "#6B7280",
    fontSize: 13,
  },
  metaBold: {
    color: "#475569",
    fontSize: 13,
    fontWeight: "700",
  },
  statsRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 10,
  },
  halfCard: {
    flex: 1,
    backgroundColor: "#F5F5F5",
    borderRadius: 14,
    padding: 12,
    minHeight: 110,
  },
  cardLabel: {
    fontSize: 12,
    color: "#6B7280",
    marginBottom: 6,
  },
  bigValue: {
    fontSize: 18,
    color: "#111827",
    fontWeight: "800",
  },
  progressTrack: {
    marginTop: 10,
    height: 6,
    borderRadius: 999,
    backgroundColor: "#DDE3F0",
    overflow: "hidden",
  },
  progressFill: {
    width: "76%",
    height: "100%",
    backgroundColor: "#0B3D91",
    borderRadius: 999,
  },
  smallHint: {
    marginTop: 8,
    fontSize: 11,
    color: "#64748B",
    lineHeight: 16,
  },
  explainCard: {
    marginTop: 10,
    backgroundColor: "#F5F5F5",
    borderRadius: 14,
    padding: 14,
  },
  explainTitle: {
    fontSize: 18,
    color: "#111827",
    fontWeight: "800",
    marginBottom: 8,
  },
  sectionSub: {
    fontSize: 13,
    color: "#374151",
    fontWeight: "700",
    marginTop: 4,
    marginBottom: 6,
  },
  emptyTop3Text: {
    marginTop: 8,
  },
  sectionSubTipburn: {
    fontSize: 13,
    color: "#374151",
    fontWeight: "700",
    marginTop: 16,
    marginBottom: 6,
  },
  rowBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
  },
  rowLeft: {
    color: "#111827",
    fontSize: 14,
  },
  rowRight: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "800",
  },
  primaryBtn: {
    marginTop: 14,
    height: 48,
    borderRadius: 12,
    backgroundColor: "#0B3D91",
    justifyContent: "center",
    alignItems: "center",
  },
  primaryBtnText: {
    color: "#fff",
    fontSize: 15,
    fontWeight: "800",
  },
  secondaryBtn: {
    marginTop: 10,
    height: 48,
    borderRadius: 12,
    borderWidth: 1.2,
    borderColor: "#D1D5DB",
    backgroundColor: "#F8FAFC",
    justifyContent: "center",
    alignItems: "center",
  },
  secondaryBtnText: {
    color: "#374151",
    fontSize: 15,
    fontWeight: "700",
  },
});